src/Entity/Documents.php
<?php

namespace App\Entity;

use App\Repository\DocumentsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DocumentsRepository::class)
 */
class Documents
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $doc_pdf;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDocPdf(): ?string
    {
        return $this->doc_pdf;
    }

    public function setDocPdf(string $doc_pdf): self
    {
        $this->doc_pdf = $doc_pdf;

        return $this;
    }
}

src/Controller/DocumentsController.php
<?php

namespace App\Controller;

use App\Entity\Documents;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DocumentsController extends AbstractController
{
    /**
     * @Route("/documents", name="documents")
     */
    public function index(): Response
    {
        $document = $this->getDoctrine()
            ->getRepository(Documents::class)
            ->findAll();


        return $this->render('documents/index.html.twig', [
            'documents' => $document,
        ]);
    }
}

templates/documents/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DocumentsController!{% endblock %}

   {% block stylesheets %}
       {{ encore_entry_link_tags('document') }}
   {% endblock %}

{% block body %}
    <div class="content">
    {% for document in documents %}
        <object type="application/pdf" width="100%" height="100%">
            <param name="src" value="{{ document.name }}" />
            <section class="content-aligned">
                <img src="{{ asset('build/cv-picture.png') }}" class="border border-4 border-secondary m-5 background-image" alt="cv">
                <div class="title-center text-bold"><a href="{{ document.docPdf }}" target="_blank">Cliquez ici pour télécharger le fichier PDF.</a>
                    <br> <p class="text-center fw-bolder">{{ document.name }}</p></div>
            </section>
        </object>
    {% endfor %}
    </div>
{% endblock %}