src/Entity/Formations.php
<?php

namespace App\Entity;

use App\Repository\FormationsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationsRepository::class)
 */
class Formations
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $school_name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $logo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $years;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSchoolName(): ?string
    {
        return $this->school_name;
    }

    public function setSchoolName(string $school_name): self
    {
        $this->school_name = $school_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getYears(): ?string
    {
        return $this->years;
    }

    public function setYears(string $years): self
    {
        $this->years = $years;

        return $this;
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Formations;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FormationController extends AbstractController
{
    /**
     * @Route("/formation", name="formation")
     */
    public function index(): Response
    {
        $formation = $this->getDoctrine()
            ->getRepository(Formations::class)
            ->findAll();


        return $this->render('formation/index.html.twig', [
            'formations' => $formation,
        ]);
    }
}

templates/formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Portfolio'Madjoula | Mes formations{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('formation') }}
{% endblock %}

{% block body %}
    <div class="formation-container">
        <div class="container-header">
            <h2 class="header_title">Mes formations</h2>
            <h3 class="header_subtitle">A partir de l'obtention de mon bac Es en 2017</h3>
        </div>
        <div class="container-body">
            {% for formation in formations %}
                    <div class="item m-3">
                        <div class="text-center"><img class="item-img" src="{{ asset(formation.logo) }}" alt="logo-{{ formation.schoolName }}"/>
                            <h2 class="title text-center">{{ formation.years }}</h2>
                            <p class="description">{{ formation.description }}</p>
                        </div>
                    </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}